name: 1. Setup Master Environment (Cache Arsenal)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # يعمل تلقائياً فجر كل يوم أحد لتحديث الأدوات

jobs:
  build-master-cache:
    runs-on: macos-latest
    steps:
      - name: Generate Dynamic Cache Key
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Setup Ultimate Master Cache
        uses: actions/cache@v4
        with:
          path: ~/ios_master_env
          key: ios-master-cache-${{ steps.date.outputs.date }}

      - name: Download The Ultimate Tools
        run: |
          mkdir -p ~/ios_master_env/tools
          
          echo "1. تثبيت ldid فقط عبر brew..."
          brew update
          brew install ldid
          cp $(which ldid) ~/ios_master_env/tools/
          
          echo "2. تحميل class-dump مباشرة من مستودعات الهندسة العكسية..."
          curl -L "https://raw.githubusercontent.com/AloneMonkey/MonkeyDev/master/bin/class-dump" -o class-dump
          chmod +x class-dump
          mv class-dump ~/ios_master_env/tools/
          
          echo "3. تحميل zsign (للتوقيع والحقن المباشر)..."
          git clone https://github.com/zhlynn/zsign.git
          cd zsign && clang++ *.cpp common/*.cpp -lcrypto -O3 -o zsign
          cp zsign ~/ios_master_env/tools/
          cd ..
          
          echo "4. تحميل بيئة Theos الشاملة..."
          git clone --recursive https://github.com/theos/theos.git ~/ios_master_env/theos
          git clone https://github.com/theos/sdks.git ~/ios_master_env/theos/sdks
          
          echo "تم تجهيز المستودع وحفظه في الكاش بنجاح!"
