name: 3. Compile And Sign Custom Dylib

on:
  push:
    paths:
      - 'source/*.m'  
      - 'source/*.x'  

jobs:
  build_and_sign:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Ultimate Master Cache
        uses: actions/cache/restore@v4
        with:
          path: ~/ios_master_env
          key: ios-master-cache-latest-run
          restore-keys: |
            ios-master-cache-

      - name: Add Arsenal to PATH
        run: echo "$HOME/ios_master_env/tools" >> $GITHUB_PATH

      - name: Compile Code to Dylib
        run: |
          APPLE_SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          THEOS_INCLUDE="$HOME/ios_master_env/theos/include"

          echo "Using Official Apple SDK: $APPLE_SDK"

          clang -dynamiclib -arch arm64 -isysroot $APPLE_SDK \
            -miphoneos-version-min=14.0 \
            -I$THEOS_INCLUDE \
            -framework Foundation \
            -framework UIKit \
            -framework CoreGraphics \
            -o MyCustomTweak.dylib source/*.m
            
          echo "تم بناء الـ Dylib بنجاح!"

      - name: Install Dependencies & Sign
        run: |
          echo "جاري تثبيت حزم التوقيع الأساسية (ldid & libplist)..."
          brew install ldid
          
          echo "جاري توقيع الملف ليعمل على أجهزة iOS..."
          ldid -S MyCustomTweak.dylib
          echo "تم التوقيع بنجاح!"
          
      - name: Upload Final Signed Dylib
        uses: actions/upload-artifact@v4
        with:
          name: Ready-To-Use-Signed-Dylib
          path: MyCustomTweak.dylib
